export const PROFESSIONS = [
  "Plomero",
  "Electricista",
  "Albañil",
  "Pintor",
  "Carpintero",
  "Herrero",
  "Impermeabilizador",
  "Técnico en Refrigeración",
  "Cerrajero",
  "Jardinería y Paisajismo",
  "Limpieza Profunda",
  "Instalador de Gas",
  "Otro",
] as const

export type Profession = (typeof PROFESSIONS)[number]

export const ESTADOS_MEXICO = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "CDMX",
  "Coahuila",
  "Colima",
  "Durango",
  "Estado de México",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas",
] as const
